create table IF NOT EXISTS "briefing" (
    "campaign_id" varchar(7), 
    "campaign_name" varchar(85), 
    "submission_date" varchar(16), 
    "description" text, 
    "campaign_objectives" varchar(192), 
    "kpis" varchar(39), 
    "placements" varchar(78),
    "startdate" varchar(10), 
    "enddate" varchar(10),
    "serving_locations" varchar(35),
    "blackwhiteaudience_list_included" varchar(95), 
    "delivery_requirements_blackaudiencewhite_list" varchar(155) null, 
    "cost_centre" varchar(4), 
    "currency" varchar(3), 
    "buy_rate_cpe" real null, 
    "volume_agreed" real null, 
    "gross_costbudget" real null, 
    "agency_fee" varchar(10) null, 
    "percentage" integer null, 
    "flat_fee" real null, 
    "net_cost" real null)